/**
 * @file Automatically generated by barrelsby.
 * Manually adjusted for ESLint plugin compatibility.
 */

import { eslintPluginNoEmoji } from "./eslint-plugin-no-emoji";
export { eslintPluginNoEmoji };
