/**
 * Translation Dictionary - Fast phrase-level lookup from pre-built dictionary
 *
 * The dictionary is a static JSON file generated by build-translation-dictionary.ts
 * It provides instant lookups without API calls or file I/O.
 *
 * Canonical phrases (official Bandai translations) are stored separately and
 * persisted immediately to survive crashes.
 */

import { promises as fs, existsSync } from "node:fs";
import path from "node:path";

import { CANONICAL_PHRASES_PATH } from "./constants";

// ============================================================================
// Types
// ============================================================================

export interface WordMapping {
  ja: string;
  en: string;
  frequency: number;
  contexts: string[];
}

export interface PhraseMapping {
  ja: string;
  en: string;
  category?: string;
}

export interface DiscoveredPattern {
  name: string;
  pattern: string;
  examples: Array<{ ja: string; en: string }>;
  frequency: number;
}

export interface DictionaryStats {
  totalFiles: number;
  uniquePhrases: number;
  uniqueWords: number;
  discoveredPatterns: number;
  processedAt: string;
}

export interface TranslationDictionary {
  version: string;
  stats: DictionaryStats;
  phrases: PhraseMapping[];
  words: WordMapping[];
  patterns: DiscoveredPattern[];
}

// ============================================================================
// Dictionary Loader
// ============================================================================

let cachedDictionary: TranslationDictionary | null = null;
let phraseIndex: Map<string, PhraseMapping> | null = null;
let wordIndex: Map<string, WordMapping> | null = null;

/** Canonical phrases loaded from disk (official Bandai translations) */
const canonicalPhrases = new Map<string, PhraseMapping>();
/** Flag to track if canonical phrases need saving */
let canonicalPhrasesDirty = false;

/**
 * Load the translation dictionary from disk
 * Caches in memory for fast subsequent lookups
 * Also loads canonical phrases (official Bandai translations)
 */
export async function loadDictionary(dictionaryPath?: string): Promise<TranslationDictionary> {
	if (cachedDictionary) {
		return cachedDictionary;
	}

	const dictPath = dictionaryPath ?? findDictionaryPath();
	if (!dictPath) {
		throw new Error("Dictionary file not found. Please ensure a dictionary file exists at one of the expected locations.");
	}
	const content = await fs.readFile(dictPath, "utf8");
	cachedDictionary = JSON.parse(content) as TranslationDictionary;

	// Build indexes for O(1) lookups
	phraseIndex = new Map();
	for (const phrase of cachedDictionary.phrases) {
		phraseIndex.set(phrase.ja, phrase);
	}

	wordIndex = new Map();
	for (const word of cachedDictionary.words) {
		wordIndex.set(word.ja, word);
	}

	// Load canonical phrases (these override dictionary phrases)
	await loadCanonicalPhrases();

	return cachedDictionary;
}

/**
 * Find the dictionary path based on common locations
 */
function findDictionaryPath(): string | undefined {
	// Try common locations
	const locations = [
		"data/src/translations/dictionary.json",
		"../../data/src/translations/dictionary.json",
		"../../../data/src/translations/dictionary.json",
		path.join(process.cwd(), "data/src/translations/dictionary.json"),
	];

	// Check each location to see if file exists
	for (const location of locations) {
		if (existsSync(location)) {
			return location;
		}
	}

	// No valid location found
	return undefined;
}

/**
 * Look up a phrase in the dictionary
 * Checks canonical phrases first (official translations), then dictionary
 * Returns the English translation if found, null otherwise
 */
export function lookupPhrase(jaText: string): PhraseMapping | null {
	// Check canonical phrases first (higher priority)
	const canonical = canonicalPhrases.get(jaText);
	if (canonical) {
		return canonical;
	}

	// Fall back to dictionary
	if (!phraseIndex) {
		return null;
	}
	return phraseIndex.get(jaText) ?? null;
}

/**
 * Look up a word in the dictionary
 * Returns the word mapping with frequency info if found
 */
export function lookupWord(jaText: string): WordMapping | null {
	if (!wordIndex) {
		return null;
	}
	return wordIndex.get(jaText) ?? null;
}

/**
 * Check if dictionary is loaded
 */
export function isDictionaryLoaded(): boolean {
	return cachedDictionary !== null;
}

/**
 * Get dictionary statistics
 */
export function getDictionaryStats(): DictionaryStats | null {
	return cachedDictionary?.stats ?? null;
}

/**
 * Get all patterns from the dictionary
 */
export function getPatterns(): DiscoveredPattern[] {
	return cachedDictionary?.patterns ?? [];
}

/**
 * Clear the cached dictionary (for testing or reloading)
 */
export function clearDictionaryCache(): void {
	cachedDictionary = null;
	phraseIndex = null;
	wordIndex = null;
	canonicalPhrases.clear();
	canonicalPhrasesDirty = false;
}

/**
 * Add a canonical phrase (official translation from Bandai)
 * Persists immediately to disk to survive crashes
 * Also adds to in-memory dictionary for immediate use
 */
export async function addPhrase(ja: string, en: string, category?: string): Promise<void> {
	// Skip if already exists with same translation
	const existing = canonicalPhrases.get(ja);
	if (existing?.en === en) {
		return;
	}

	const phrase: PhraseMapping = { ja, en, category };

	// Add to canonical phrases (persisted)
	canonicalPhrases.set(ja, phrase);
	canonicalPhrasesDirty = true;

	// Also add to in-memory dictionary for immediate lookups
	if (cachedDictionary && phraseIndex) {
		if (!phraseIndex.has(ja)) {
			cachedDictionary.phrases.push(phrase);
			cachedDictionary.stats.uniquePhrases++;
		}
		phraseIndex.set(ja, phrase);
	}

	// Persist immediately
	await saveCanonicalPhrases();
}

/**
 * Synchronous version of addPhrase for compatibility
 * Queues the save operation without awaiting
 */
export function addPhraseSync(ja: string, en: string, category?: string): void {
	const existing = canonicalPhrases.get(ja);
	if (existing?.en === en) {
		return;
	}

	const phrase: PhraseMapping = { ja, en, category };
	canonicalPhrases.set(ja, phrase);
	canonicalPhrasesDirty = true;

	if (cachedDictionary && phraseIndex) {
		if (!phraseIndex.has(ja)) {
			cachedDictionary.phrases.push(phrase);
			cachedDictionary.stats.uniquePhrases++;
		}
		phraseIndex.set(ja, phrase);
	}

	// Queue save without awaiting (fire and forget)
	void saveCanonicalPhrases();
}

// ============================================================================
// Canonical Phrases Persistence
// ============================================================================

/**
 * Load canonical phrases from disk
 * These are official Bandai translations that take priority over dictionary
 */
async function loadCanonicalPhrases(): Promise<void> {
	try {
		if (!existsSync(CANONICAL_PHRASES_PATH)) {
			return;
		}
		const content = await fs.readFile(CANONICAL_PHRASES_PATH, "utf8");
		const data = JSON.parse(content) as { phrases: PhraseMapping[] };

		canonicalPhrases.clear();
		for (const phrase of data.phrases) {
			canonicalPhrases.set(phrase.ja, phrase);
			// Also add to phrase index for unified lookup
			if (phraseIndex) {
				phraseIndex.set(phrase.ja, phrase);
			}
		}
		canonicalPhrasesDirty = false;
	} catch {
		// File doesn't exist or is invalid, start fresh
		canonicalPhrases.clear();
	}
}

/**
 * Save canonical phrases to disk
 * Called after each addPhrase to ensure persistence
 */
async function saveCanonicalPhrases(): Promise<void> {
	if (!canonicalPhrasesDirty) {
		return;
	}

	const data = {
		version: "1.0",
		updatedAt: new Date().toISOString(),
		phrases: [...canonicalPhrases.values()],
	};

	// Ensure directory exists
	await fs.mkdir(path.dirname(CANONICAL_PHRASES_PATH), { recursive: true });
	await fs.writeFile(CANONICAL_PHRASES_PATH, JSON.stringify(data, null, 2), "utf8");
	canonicalPhrasesDirty = false;
}

/**
 * Get count of canonical phrases
 */
export function getCanonicalPhraseCount(): number {
	return canonicalPhrases.size;
}
