/**
 * Translation Dictionary - Fast phrase-level lookup from pre-built dictionary
 *
 * The dictionary is a static JSON file generated by build-translation-dictionary.ts
 * It provides instant lookups without API calls or file I/O.
 */

import { promises as fs } from 'node:fs';
import { join } from 'node:path';

// ============================================================================
// Types
// ============================================================================

export interface WordMapping {
  ja: string;
  en: string;
  frequency: number;
  contexts: string[];
}

export interface PhraseMapping {
  ja: string;
  en: string;
  category?: string;
}

export interface DiscoveredPattern {
  name: string;
  pattern: string;
  examples: Array<{ ja: string; en: string }>;
  frequency: number;
}

export interface DictionaryStats {
  totalFiles: number;
  uniquePhrases: number;
  uniqueWords: number;
  discoveredPatterns: number;
  processedAt: string;
}

export interface TranslationDictionary {
  version: string;
  stats: DictionaryStats;
  phrases: PhraseMapping[];
  words: WordMapping[];
  patterns: DiscoveredPattern[];
}

// ============================================================================
// Dictionary Loader
// ============================================================================

let cachedDictionary: TranslationDictionary | null = null;
let phraseIndex: Map<string, PhraseMapping> | null = null;
let wordIndex: Map<string, WordMapping> | null = null;

/**
 * Load the translation dictionary from disk
 * Caches in memory for fast subsequent lookups
 */
export async function loadDictionary(dictionaryPath?: string): Promise<TranslationDictionary> {
  if (cachedDictionary) {
    return cachedDictionary;
  }

  const path = dictionaryPath || findDictionaryPath();
  const content = await fs.readFile(path, 'utf-8');
  cachedDictionary = JSON.parse(content) as TranslationDictionary;

  // Build indexes for O(1) lookups
  phraseIndex = new Map();
  for (const phrase of cachedDictionary.phrases) {
    phraseIndex.set(phrase.ja, phrase);
  }

  wordIndex = new Map();
  for (const word of cachedDictionary.words) {
    wordIndex.set(word.ja, word);
  }

  return cachedDictionary;
}

/**
 * Find the dictionary path based on common locations
 */
function findDictionaryPath(): string {
  // Try common locations
  const locations = [
    'data/translations/dictionary.json',
    '../../data/translations/dictionary.json',
    '../../../data/translations/dictionary.json',
    join(process.cwd(), 'data/translations/dictionary.json'),
  ];

  // Return first location (will error if not found)
  return locations[0];
}

/**
 * Look up a phrase in the dictionary
 * Returns the English translation if found, null otherwise
 */
export function lookupPhrase(jaText: string): PhraseMapping | null {
  if (!phraseIndex) {
    return null;
  }
  return phraseIndex.get(jaText) || null;
}

/**
 * Look up a word in the dictionary
 * Returns the word mapping with frequency info if found
 */
export function lookupWord(jaText: string): WordMapping | null {
  if (!wordIndex) {
    return null;
  }
  return wordIndex.get(jaText) || null;
}

/**
 * Check if dictionary is loaded
 */
export function isDictionaryLoaded(): boolean {
  return cachedDictionary !== null;
}

/**
 * Get dictionary statistics
 */
export function getDictionaryStats(): DictionaryStats | null {
  return cachedDictionary?.stats || null;
}

/**
 * Get all patterns from the dictionary
 */
export function getPatterns(): DiscoveredPattern[] {
  return cachedDictionary?.patterns || [];
}

/**
 * Clear the cached dictionary (for testing or reloading)
 */
export function clearDictionaryCache(): void {
  cachedDictionary = null;
  phraseIndex = null;
  wordIndex = null;
}

/**
 * Add a new phrase to the in-memory dictionary
 * Note: This does NOT persist to disk - use build-translation-dictionary.ts to regenerate
 */
export function addPhrase(ja: string, en: string, category?: string): void {
  if (!cachedDictionary || !phraseIndex) {
    return;
  }

  const phrase: PhraseMapping = { ja, en, category };
  cachedDictionary.phrases.push(phrase);
  phraseIndex.set(ja, phrase);
  cachedDictionary.stats.uniquePhrases++;
}
