/**
 * Graph-based Zod schema for universal hobby configuration
 * Uses flexible arbitrary properties with relationship-based structure
 */

import { z } from "zod";

// Graph node types
const NodeTypeEnum = z.enum([
	"hobby_type",
	"brand",
	"scale",
	"category",
	"property",
	"attribute",
	"field",
	"value",
]);

// Relationship types
const RelationshipTypeEnum = z.enum([
	"HAS_BRAND",
	"HAS_SCALE",
	"HAS_CATEGORY",
	"HAS_PROPERTY",
	"HAS_FIELD",
	"HAS_VALUE",
	"RELATES_TO",
	"INSTANCE_OF",
	"SUBTYPE_OF",
]);

// Arbitrary property value types
const PropertyValue = z.union([
	z.string(),
	z.number(),
	z.boolean(),
	z.array(z.unknown()),
	z.record(z.unknown()),
	z.date(),
	z.null(),
]);

// Graph node schema
const GraphNode = z.object({
	id: z.string(),
	type: NodeTypeEnum,
	properties: z.record(PropertyValue).optional(),
	metadata: z.object({
		createdAt: z.string().datetime().optional(),
		updatedAt: z.string().datetime().optional(),
		version: z.string().optional(),
	}).optional(),
});

// Graph relationship schema
const GraphRelationship = z.object({
	id: z.string(),
	type: RelationshipTypeEnum,
	fromNode: z.string(), // node ID
	toNode: z.string(),   // node ID
	properties: z.record(PropertyValue).optional(),
	metadata: z.object({
		createdAt: z.string().datetime().optional(),
		updatedAt: z.string().datetime().optional(),
	}).optional(),
});

// Complete graph structure
const HobbyGraph = z.object({
	nodes: z.array(GraphNode),
	relationships: z.array(GraphRelationship),
	schemas: z.record(z.unknown()).optional(), // JSON schemas generated by Zod
	metadata: z.object({
		version: z.string().default("1.0.0"),
		createdAt: z.string().datetime(),
		updatedAt: z.string().datetime(),
		description: z.string().optional(),
	}),
});

// Helper schemas for common patterns
const HobbyTypeNode = GraphNode.extend({
	type: z.literal(NodeTypeEnum.enum.hobby_type),
	properties: z.object({
		name: z.string(),
		description: z.string(),
		icon: z.string().optional(),
		color: z.string().optional(),
		isActive: z.boolean().default(true),
	}).passthrough(), // Allow arbitrary additional properties
});

const BrandNode = GraphNode.extend({
	type: z.literal(NodeTypeEnum.enum.brand),
	properties: z.object({
		name: z.string(),
		website: z.string().url().optional(),
		founded: z.number().optional(),
		country: z.string().optional(),
	}).passthrough(),
});

const ScaleNode = GraphNode.extend({
	type: z.literal(NodeTypeEnum.enum.scale),
	properties: z.object({
		name: z.string(),
		description: z.string().optional(),
		ratio: z.string().optional(),
	}).passthrough(),
});

const FieldNode = GraphNode.extend({
	type: z.literal(NodeTypeEnum.enum.field),
	properties: z.object({
		name: z.string(),
		fieldType: z.enum(["text", "select", "multiselect", "number", "currency", "date", "boolean", "url", "textarea"]),
		required: z.boolean().default(false),
		searchable: z.boolean().default(false),
		filterable: z.boolean().default(false),
		displayInList: z.boolean().default(false),
		displayInDetail: z.boolean().default(true),
		order: z.number().default(0),
	}).passthrough(),
});

// Utility functions for working with the graph
export class HobbyGraphManager {
	constructor(private graph: HobbyGraph) {}

	// Get all nodes of a specific type
	getNodesByType(type: NodeTypeEnum): GraphNode[] {
		return this.graph.nodes.filter(node => node.type === type);
	}

	// Get relationships from a node
	getRelationshipsFrom(nodeId: string, type?: RelationshipTypeEnum): GraphRelationship[] {
		return this.graph.relationships.filter(rel =>
			rel.fromNode === nodeId && (!type || rel.type === type),
		);
	}

	// Get relationships to a node
	getRelationshipsTo(nodeId: string, type?: RelationshipTypeEnum): GraphRelationship[] {
		return this.graph.relationships.filter(rel =>
			rel.toNode === nodeId && (!type || rel.type === type),
		);
	}

	// Get connected nodes
	getConnectedNodes(nodeId: string, relationshipType?: RelationshipTypeEnum): GraphNode[] {
		const relationships = this.getRelationshipsFrom(nodeId, relationshipType);
		return relationships
			.map(rel => this.graph.nodes.find(node => node.id === rel.toNode))
			.filter((node): node is GraphNode => node !== undefined);
	}

	// Get hobby type with all its relationships
	getHobbyTypeWithDetails(hobbyTypeId: string): {
    node: GraphNode;
    brands: GraphNode[];
    scales: GraphNode[];
    categories: GraphNode[];
    fields: GraphNode[];
  } | null {
		const node = this.graph.nodes.find(n => n.id === hobbyTypeId);
		if (!node || node.type !== NodeTypeEnum.enum.hobby_type) return null;

		return {
			node,
			brands: this.getConnectedNodes(hobbyTypeId, RelationshipTypeEnum.enum.HAS_BRAND),
			scales: this.getConnectedNodes(hobbyTypeId, RelationshipTypeEnum.enum.HAS_SCALE),
			categories: this.getConnectedNodes(hobbyTypeId, RelationshipTypeEnum.enum.HAS_CATEGORY),
			fields: this.getConnectedNodes(hobbyTypeId, RelationshipTypeEnum.enum.HAS_FIELD),
		};
	}

	// Validate that all relationships reference existing nodes
	validateRelationships(): { valid: boolean; errors: string[] } {
		const errors: string[] = [];
		const nodeIds = new Set(this.graph.nodes.map(node => node.id));

		for (const relationship of this.graph.relationships) {
			if (!nodeIds.has(relationship.fromNode)) {
				errors.push(`Relationship ${relationship.id} references non-existent fromNode: ${relationship.fromNode}`);
			}
			if (!nodeIds.has(relationship.toNode)) {
				errors.push(`Relationship ${relationship.id} references non-existent toNode: ${relationship.toNode}`);
			}
		}

		return { valid: errors.length === 0, errors };
	}

	// Transform graph to legacy format for backward compatibility
	toLegacyFormat(): any[] {
		const hobbyTypes = this.getNodesByType(NodeTypeEnum.enum.hobby_type);

		return hobbyTypes.map(hobbyType => {
			const details = this.getHobbyTypeWithDetails(hobbyType.id);
			if (!details) return null;

			return {
				id: hobbyType.id,
				name: hobbyType.properties.name,
				description: hobbyType.properties.description,
				icon: hobbyType.properties.icon,
				color: hobbyType.properties.color,
				brands: details.brands.map(brand => brand.properties.name),
				scales: details.scales.map(scale => scale.properties.name),
				fields: details.fields.map(field => ({
					id: field.id,
					name: field.properties.name,
					key: field.id,
					type: field.properties.fieldType,
					required: field.properties.required,
					searchable: field.properties.searchable,
					filterable: field.properties.filterable,
					displayInList: field.properties.displayInList,
					displayInDetail: field.properties.displayInDetail,
					order: field.properties.order,
					...field.properties, // Include any additional arbitrary properties
				})),
				...hobbyType.properties, // Include any additional hobby type properties
			};
		}).filter(Boolean);
	}
}

// Type exports
export type HobbyGraphType = z.infer<typeof HobbyGraph>;
export type GraphNodeType = z.infer<typeof GraphNode>;
export type GraphRelationshipType = z.infer<typeof GraphRelationship>;
export type HobbyTypeNodeType = z.infer<typeof HobbyTypeNode>;
export type BrandNodeType = z.infer<typeof BrandNode>;
export type ScaleNodeType = z.infer<typeof ScaleNode>;
export type FieldNodeType = z.infer<typeof FieldNode>;

// Schema exports
export {
	HobbyGraph,
	GraphNode,
	GraphRelationship,
	HobbyTypeNode,
	BrandNode,
	ScaleNode,
	FieldNode,
	NodeTypeEnum,
	RelationshipTypeEnum,
};

// Validation helper functions
export const validateHobbyGraph = (data: unknown) => {
	const result = HobbyGraph.safeParse(data);
	if (result.success) {
		const manager = new HobbyGraphManager(result.data);
		const validation = manager.validateRelationships();
		if (!validation.valid) {
			return {
				success: false,
				error: `Invalid relationships: ${validation.errors.join(", ")}`,
			};
		}
	}
	return result;
};