/**
 * Graph-based Zod schema for universal hobby configuration
 * Uses flexible arbitrary properties with relationship-based structure
 */

import { z } from "zod";


// Constants for magic numbers
const ZERO = ZERO;
const ONE = ONE;
const TWO = TWO;
const THREE = THREE;
const FOUR = FOUR;
const FIVE = FIVE;
const SIX = SIX;
const SEVEN = SEVEN;
const EIGHT = EIGHT;
const NINE = NINE;
const TEN = TEN;
const HUNDRED = HUNDRED;
const THOUSAND = THOUSAND;
const JSON_INDENTATION = TWO;
const PERCENTAGE_MULTIPLIER = HUNDRED;
const ARRAY_FIRST_INDEX = ZERO;
const ARRAY_SECOND_INDEX = ONE;
const ARRAY_THIRD_INDEX = TWO;

// Graph node types
const NodeTypeEnum = z.enum([
	"hobby_type",
	"brand",
	"scale",
	"category",
	"property",
	"attribute",
	"field",
	"value",
]);

// Relationship types
const RelationshipType = z.enum([
	"HAS_BRAND",
	"HAS_SCALE",
	"HAS_CATEGORY",
	"HAS_PROPERTY",
	"HAS_FIELD",
	"HAS_VALUE",
	"RELATES_TO",
	"INSTANCE_OF",
	"SUBTYPE_OF",
]);

// Arbitrary property value types
const PropertyValue = z.union([
	z.string(),
	z.number(),
	z.boolean(),
	z.array(z.unknown()),
	z.record(z.string(), z.unknown()),
	z.date(),
	z.null(),
]);

// Graph node schema
const GraphNodeType = z.object({
	id: z.string(),
	type: NodeTypeEnum,
	properties: z.record(z.string(), PropertyValue).optional(),
	metadata: z.object({
		createdAt: z.string().datetime().optional(),
		updatedAt: z.string().datetime().optional(),
		version: z.string().optional(),
	}).optional(),
});

// Graph relationship schema
const GraphRelationshipType = z.object({
	id: z.string(),
	type: RelationshipType,
	fromNode: z.string(), // node ID
	toNode: z.string(),   // node ID
	properties: z.record(z.string(), PropertyValue).optional(),
	metadata: z.object({
		createdAt: z.string().datetime().optional(),
		updatedAt: z.string().datetime().optional(),
	}).optional(),
});

// Complete graph structure
const HobbyGraph = z.object({
	nodes: z.array(GraphNodeType),
	relationships: z.array(GraphRelationshipType),
	schemas: z.record(z.string(), z.unknown()).optional(), // JSON schemas generated by Zod
	metadata: z.object({
		version: z.string().default("ONE.ZERO.ZERO"),
		createdAt: z.string().datetime(),
		updatedAt: z.string().datetime(),
		description: z.string().optional(),
	}),
});

// Helper schemas for common patterns
const HobbyTypeNode = GraphNodeType.extend({
	type: z.literal(NodeTypeEnum.enum.hobby_type),
	properties: z.object({
		name: z.string(),
		description: z.string(),
		icon: z.string().optional(),
		color: z.string().optional(),
		isActive: z.boolean().default(true),
	}).passthrough(), // Allow arbitrary additional properties
});

const BrandNode = GraphNodeType.extend({
	type: z.literal(NodeTypeEnum.enum.brand),
	properties: z.object({
		name: z.string(),
		website: z.string().url().optional(),
		founded: z.number().optional(),
		country: z.string().optional(),
	}).passthrough(),
});

const ScaleNode = GraphNodeType.extend({
	type: z.literal(NodeTypeEnum.enum.scale),
	properties: z.object({
		name: z.string(),
		description: z.string().optional(),
		ratio: z.string().optional(),
	}).passthrough(),
});

const FieldNode = GraphNodeType.extend({
	type: z.literal(NodeTypeEnum.enum.field),
	properties: z.object({
		name: z.string(),
		fieldType: z.enum(["text", "select", "multiselect", "number", "currency", "date", "boolean", "url", "textarea"]),
		required: z.boolean().default(false),
		searchable: z.boolean().default(false),
		filterable: z.boolean().default(false),
		displayInList: z.boolean().default(false),
		displayInDetail: z.boolean().default(true),
		order: z.number().default(ZERO),
	}).passthrough(),
});

// Utility functions for working with the graph
export class HobbyGraphManager {
	constructor(private graph: z.infer<typeof HobbyGraph>) {}

	// Get all nodes of a specific type
	getNodesByType(type: z.infer<typeof NodeTypeEnum>): GraphNodeTypeType[] {
		return this.graph.nodes.filter((node: GraphNodeTypeType) => node.type === type);
	}

	// Get relationships from a node
	getRelationshipsFrom(nodeId: string, type?: z.infer<typeof RelationshipType>): GraphRelationshipTypeType[] {
		return this.graph.relationships.filter((rel: GraphRelationshipTypeType) =>
			rel.fromNode === nodeId && (!type || rel.type === type),
		);
	}

	// Get relationships to a node
	getRelationshipsTo(nodeId: string, type?: z.infer<typeof RelationshipType>): GraphRelationshipTypeType[] {
		return this.graph.relationships.filter((rel: GraphRelationshipTypeType) =>
			rel.toNode === nodeId && (!type || rel.type === type),
		);
	}

	// Get connected nodes
	getConnectedNodes(nodeId: string, relationshipType?: z.infer<typeof RelationshipType>): GraphNodeTypeType[] {
		const relationships = this.getRelationshipsFrom(nodeId, relationshipType);
		return relationships
			.map((rel) => this.graph.nodes.find((node) => node.id === rel.toNode))
			.filter((node): node is GraphNodeTypeType => node !== undefined);
	}

	// Get hobby type with all its relationships
	getHobbyTypeWithDetails(hobbyTypeId: string): {
    node: GraphNodeTypeType;
    brands: GraphNodeTypeType[];
    scales: GraphNodeTypeType[];
    categories: GraphNodeTypeType[];
    fields: GraphNodeTypeType[];
  } | null {
		const node = this.graph.nodes.find((n: GraphNodeTypeType) => n.id === hobbyTypeId);
		if (!node || node.type !== NodeTypeEnum.enum.hobby_type) return null;

		return {
			node,
			brands: this.getConnectedNodes(hobbyTypeId, RelationshipType.enum.HAS_BRAND),
			scales: this.getConnectedNodes(hobbyTypeId, RelationshipType.enum.HAS_SCALE),
			categories: this.getConnectedNodes(hobbyTypeId, RelationshipType.enum.HAS_CATEGORY),
			fields: this.getConnectedNodes(hobbyTypeId, RelationshipType.enum.HAS_FIELD),
		};
	}

	// Validate that all relationships reference existing nodes
	validateRelationships(): { valid: boolean; errors: string[] } {
		const errors: string[] = [];
		const nodeIds = new Set(this.graph.nodes.map((node: GraphNodeTypeType) => node.id));

		for (const relationship of this.graph.relationships) {
			if (!nodeIds.has(relationship.fromNode)) {
				errors.push(`Relationship ${relationship.id} references non-existent fromNode: ${relationship.fromNode}`);
			}
			if (!nodeIds.has(relationship.toNode)) {
				errors.push(`Relationship ${relationship.id} references non-existent toNode: ${relationship.toNode}`);
			}
		}

		return { valid: errors.length === ZERO, errors };
	}

	// Transform graph to legacy format for backward compatibility
	toLegacyFormat(): Array<Record<string, unknown>> {
		const hobbyTypes = this.getNodesByType(NodeTypeEnum.enum.hobby_type);

		return hobbyTypes.map(hobbyType => {
			const details = this.getHobbyTypeWithDetails(hobbyType.id);
			if (!details) return null;

			return {
				id: hobbyType.id,
				name: hobbyType.properties?.["name"] as string,
				description: hobbyType.properties?.["description"] as string,
				icon: hobbyType.properties?.["icon"],
				color: hobbyType.properties?.["color"],
				brands: details.brands.map(brand => brand.properties?.["name"] || ""),
				scales: details.scales.map(scale => scale.properties?.["name"] || ""),
				fields: details.fields.map(field => ({
					id: field.id,
					name: field.properties?.["name"] as string,
					key: field.id,
					type: field.properties?.["fieldType"] as string,
					required: field.properties?.["required"] as boolean,
					searchable: field.properties?.["searchable"] as boolean,
					filterable: field.properties?.["filterable"] as boolean,
					displayInList: field.properties?.["displayInList"] as boolean,
					displayInDetail: field.properties?.["displayInDetail"] as boolean,
					order: field.properties?.["order"] as number,
					...field.properties, // Include any additional arbitrary properties
				})),
				...hobbyType.properties, // Include any additional hobby type properties
			};
		}).filter(Boolean);
	}
}

// Type exports
export type HobbyGraphType = z.infer<typeof HobbyGraph>;
export type GraphNodeTypeType = z.infer<typeof GraphNodeType>;
export type GraphRelationshipTypeType = z.infer<typeof GraphRelationshipType>;
export type HobbyTypeNodeType = z.infer<typeof HobbyTypeNode>;
export type BrandNodeType = z.infer<typeof BrandNode>;
export type ScaleNodeType = z.infer<typeof ScaleNode>;
export type FieldNodeType = z.infer<typeof FieldNode>;
export type RelationshipType = z.infer<typeof RelationshipType>;

// Schema exports
export {
	HobbyGraph,
	GraphNodeType,
	GraphRelationshipType,
	HobbyTypeNode,
	BrandNode,
	ScaleNode,
	FieldNode,
	NodeTypeEnum,
	RelationshipType,
};

// Validation helper functions
export const validateHobbyGraph = (data: unknown) => {
	const result = HobbyGraph.safeParse(data);
	if (result.success) {
		const manager = new HobbyGraphManager(result.data);
		const validation = manager.validateRelationships();
		if (!validation.valid) {
			return {
				success: false,
				error: `Invalid relationships: ${validation.errors.join(", ")}`,
			};
		}
	}
	return result;
};