/**
 * @file Automatically generated by barrelsby.
 */

export * as schemas from "./schemas";

// CLI Types
export type LanguageCode = "ja" | "en" | "mixed" | "unknown";

export type LanguageDetectionMethod =
  | "html-lang-attribute"
  | "html-meta-content"
  | "http-headers"
  | "url-pattern"
  | "content-analysis"
  | "filename-pattern"
  | "manual-detection"
  | "hybrid"
  | "fallback";

export interface LanguageDetection {
  language: LanguageCode;
  confidence: number; // 0.0 - 1.0
  method: LanguageDetectionMethod;
  evidence: string[];
}

export interface PriceInfo {
  amount: number;
  currency: string;
  originalText: string;
  includesTax?: boolean;
}

export interface SpecificationValue {
  value: string | number | boolean;
  unit?: string;
  originalText: string;
}

export interface ProductImage {
  url: string;
  alt?: string;
  width?: number;
  height?: number;
  type: "main" | "gallery" | "thumbnail" | "box";
}

// Gundam-specific data interface for scraped data
export interface GundamData {
  id: string;
  name: string;
  brand?: string;
  category?: string;
  price?: number;
  currency?: string;
  releaseDate?: string;
  sku?: string;
  description?: string;
  specifications?: Record<string, unknown>;
  images: Array<{ type: string; url: string; alt: string }>;
  language: LanguageDetection;
  url?: string;
  source: string;
  scrapedAt: string;
}